../bin/./rshell << EOF
test /home/csmajs/crodr027/rshell/src/fake.cpp || echo "Expected FALSE"
test /home/csmajs/crodr027/rshellsrc/test/dog.cpp || echo "Expected FALSE"
test /home/csmajs/crodr027/rshellsrc/test/corn.cpp || echo "Expected FALSE"
test /home/csmajs/crodr027/rshell || echo "Expected TRUE"
test /home/csmajs/crodr027/rshell/cat || echo "Expected FALSE"
test -f /home/csmajs/crodr027/rshell/src/main.cpp && echo "Path exists"
test -f /home/csmajs/crodr027/rshell/src/fake.cpp || echo "Expected FALSE"
test -f /home/csmajs/crodr027/rshell/src/test/dog.cpp || echo "Expected FALSE"
test -f /home/csmajs/crodr027/rshell/src/test/corn.cpp || echo "Expected FALSE"
test -f /home/csmajs/crodr027/VIMRC_SETTINGS || echo "Expected FALSE"
test -f /home/csmajs/crodr027/rshell/ || echo "Expected FALSE"
test -d /home/csmajs/crodr027/rshell/src/test || echo "Expected FALSE"
test -d /home/csmajs/crodr027/rshell/src/fake.cpp || echo "Expected FALSE"
test -d /home/csmajs/crodr027/rshell/src/test/test2 || echo "Expected FALSE"
test -d /home/csmajs/crodr027/rshell/src/test/corn.cpp || echo "Expected FALSE"
test -d /home/csmajs/crodr027/rshell || echo "Expected TRUE"
test -d /home/csmajs/crodr027/rshell/cat || echo "Expected FALSE"
test -e /home/csmajs/crodr027/rshell/src/main.cpp && echo "Expected TRUE"
test -e /home/csmajs/crodr027/rshell/src/fake.cpp || echo "Expected FALSE"
test -e /home/csmajs/crodr027/rshell/src/test/dog.cpp || echo "Expected FALSE"
test -e /home/csmajs/crodr027/rshell/src/test/corn.cpp || echo "Expected FALSE"
test -e /home/csmajs/crodr027/rshell || echo "Expected TRUE"
test -e /home/csmajs/crodr027/rshell/cat || echo "Expected FALSE"
test -e /home/csmajs/crodr027/rshell || echo "Expected TRUE"
test -e /home/csmajs/crodr027/rshell/cat || echo "Expected FALSE"
test -e /home/csmajs/crodr027/rshell/src/main.cpp || echo "Expected TRUE"
test -e /home/csmajs/crodr027/rshell/src/main.cpp || echo "Expected TRUE"
[-e /home/csmajs/crodr027/rshell/src/main.cpp ] || echo "Expected TRUE"
[-f /home/csmajs/crodr027/rshell/src/main.cpp ] || echo "Expected TRUE"
[-d /home/csmajs/crodr027/rshell ] && echo "Expected TRUE"
[ -e /home/csmajs/crodr027/rshell/src/main.cpp && echo "Expected TRUE"
] [ -e /home/csmajs/crodr027/rshell/src/main.cpp ] && echo "Expected TRUE"
][ [ -e /home/csmajs/crodr027/rshell/src/main.cpp ] && echo "Expected TRUE"
[ -e /home/csmajs/crodr027/rshell/src/main.cpp ] && echo "Expected TRUE" ]]
exit
EOF
printf "\n"
